### ISSUE TITLE
hi , the problem is solved , but in same widiget i get error :

### ISSUE THREAD

**Issue by heshesh2010** [EdsonBueno/infinite_scroll_pagination#10]
hi , the problem is solved , but in same widiget i get error : 
There are multiple heroes that share the same tag within a subtree.

i make sure there is no hero , when i remove PagedListView the layout works fine when hit any button

_Originally posted by @heshesh2010 in https://github.com/EdsonBueno/infinite_scroll_pagination/issues/9#issuecomment-714458793_

**Comment by EdsonBueno** [comment]
Hi @heshesh2010 .
Try using a regular ListView (non-paged) with some invented data to see if the problem persists.
If the problem goes away with the regular ListView, can you reproduce the issue on a toy project and give me access to it?
Thank you!

**Comment by heshesh2010** [comment]
Hi @EdsonBueno , 

i have try ListView as u said and it's working great , but PagedListView gives me same error about heros .

so how i can give u access on my github project ?

**Comment by EdsonBueno** [comment]
Is it private? If it is, you have to invite my username (EdsonBueno) on Settings -> Manage access.

**Comment by heshesh2010** [comment]
done i have added u , the problem is in file called " menu_list.dart " it's on bottom of the page , there is comment code for ListView if you run it your will see it works

**Comment by EdsonBueno** [comment]
I couldn't run your project, there're some missing files!
**But here's my guess:** 
You didn't add any items to your ListView, that's why it "works"!
Notice that `RestaurantController.foods` is always empty!
As soon as you add some items, it breaks! Why? `FoodItemWidget` uses `Hero`.
I'm closing this issue! If you have any future questions, please contact me on [our chat](https://gitter.im/infinite_scroll_pagination/community)! Thank you!
