### ISSUE TITLE
Flutter filter data with pagination issue

### ISSUE THREAD

**Issue by KalpShah412** [EdsonBueno/infinite_scroll_pagination#105]
In my flutter project,I load the pagination list of 50 product.In that listview i want to offline search with text editing controller and filter whole list in offline mode.

I have the logic of offline search:

```
 _onProductSearchChanged() {
    if (cartSearchQueryController.text.isNotEmpty) {
      if (cartSearchQueryController.text.length > 0) {
        filteredCartSalesMarketingDetail = cartSalesMarketingDetail
            .where(
              (u) => (u.marketingName.toLowerCase().contains(
                    cartSearchQueryController.text.toLowerCase(),
                  )),
            )
            .toList();
      }
    } else {
      filteredCartSalesMarketingDetail = cartSalesMarketingDetail;
    }
}
```
It will work in normal listview but not work in infinite_scroll_pagination.

Anyone Help?

**Comment by EdsonBueno** [comment]
Hi @KalpShah412 .
This is not related to your issue, but: in paginated lists, the search filter has to take place in your remote API and not locally. What if the user is searching for something that is not in the pages you already have?

As for your issue, I assume you forgot to sent some part of your code, because you should assign `filteredCartSalesMarketingDigital` to `_pagingController.itemList`, right?

I'm closing the issue for now, but feel free to continue the discussion.
Thank you
