### ISSUE TITLE
Scroll to index 

### ISSUE THREAD

**Issue by KennyChan94P** [EdsonBueno/infinite_scroll_pagination#11]
hi, first of all, very happy to use this plugin and it is really easy to implement to my project. but i would like to know, is there a "scroll to index" functionality like after we click on the notification with list item id, i want to scroll my list to the list item.
Thanks in advance.

**Comment by EdsonBueno** [comment]
Hi @KennyChan94P , thank you for your kind words!
You could implement that in the same way you would do it with a regular `ListView` in Flutter, but using `PagedListView` instead. I can't point you to a specific approach because there are several, but a quick search on Google or StackOverflow will help you with that.
That functionality is not covered in our docs because it's nothing specific to pagination or infinite scrolling.

Thank you for opening the issue! If you still have any doubts, please [chat me](https://gitter.im/infinite_scroll_pagination/community).

**Comment by Nitingadhiya** [comment]
@brax10ward @EdsonBueno 
I've used "scroll_to_index" package but in that case we have to add height on Widget. so how we can set it? 
Because In my case I don't know height for every list of widget. 

Can you please support us, how we can fix it?
