### ISSUE TITLE
Pass error to the error builders?

### ISSUE THREAD

**Issue by hacker1024** [EdsonBueno/infinite_scroll_pagination#14]
At the moment, `PagingController.error` is only used in a null check.
It'd be great if this value could be passed into the error builders, as it's cleaner than having to fetch it from the original source in the build function.

**Comment by EdsonBueno** [comment]
In the earliest versions of the package, the error used to be included in the error builders.
I changed it because of a few points:
* People found it confusing: What's the difference between the error in the builder and the one in the `PagingController`?
* Should we include the [PagingController.retryLastRequest](https://pub.dev/documentation/infinite_scroll_pagination/latest/infinite_scroll_pagination/PagingController/retryLastRequest.html) there as well?
* What about the `noItemsFoundIndicatorBuilder`? It certainly doesn't make sense to provide an error there, but what about the `retryLastRequest` callback?

That all being said, having the `PagingController` as the single source is the best/cleaner choice.

I'm closing this issue. Thank you!
