### ISSUE TITLE
the method fires after calling dispose, even if there is a "?"

### ISSUE THREAD

**Issue by Kizat** [EdsonBueno/infinite_scroll_pagination#152]
`pagingController?.appendLastPage(products!.toList());` worked after calling `dispose` but `?` didn't help and gave an error

> _Exception (Exception: A PagingController was used after being disposed.
> Once you have called dispose() on a PagingController, it can no longer be used.
> If you’re using a Future, it probably completed after the disposal of the owning widget.
> Make sure dispose() has not been called yet before using the PagingController.)

**Comment by clragon** [comment]
the pagingController doesnt become `null` when it is disposed, so `?` doesnt help here.

An easy way of removing this error is by checking the `mounted` property of your stateful widget.

or you can ignore the error;

Flutter for some reason didnt find it necessary to include any way of checking whether a changenotifier is disposed or not, so this entire error is just non-sensical, especially since they have a value to keep track of disposal, but its private.

**Comment by EdsonBueno** [comment]
Thanks for the amazing answer @clragon .
