### ISSUE TITLE
getting this exception with new version 3.2.0

### ISSUE THREAD

**Issue by raviranjan31** [EdsonBueno/infinite_scroll_pagination#204]
Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: /root/.pub-cache/hosted/pub.dartlang.org/infinite_scroll_pagination-3.2.0/lib/src/ui/paged_sliver_builder.dart:254:33:
Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/sdks/flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance.addPostFrameCallback((_) {
                                ^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.

**Comment by elmurphy** [comment]
Same here

**Comment by elmurphy** [comment]
Just accept the pull request please

**Comment by bdaykid** [comment]
Thank you for the lib. Same issue? I revert to 3.1.0 and the problem's gone.

../../FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/infinite_scroll_pagination-3.2.0/lib/src/ui/paged_sliver_builder.dart:254:33: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../FlutterProjects/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
        WidgetsBinding.instance.addPostFrameCallback((_) {
                                ^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

**Comment by clragon** [comment]
in flutter 3.0, `WidgetsBinding.instance` is no longer nullable. 
I assume, upgrading to flutter 3 should resolve your issue.

**Comment by lohhans** [comment]
I've solved this error putting a null-check on ```/.pub-cache/hosted/pub.dartlang.org/infinite_scroll_pagination-3.2.0/lib/src/ui/paged_sliver_builder.dart``` to don't execute function if the instance is null...

On the line 254 where it's written:

> ```WidgetsBinding.instance.addPostFrameCallback((_) {``` 

change it to:

> ```WidgetsBinding.instance?.addPostFrameCallback((_) {```.

**Comment by clragon** [comment]
version 3.2.0 of this package has specifically removed that so that it removes a warning in flutter version 3.0.

please upgrade to flutter version 3.0. if you do not plan on upgrading to version 3.0, then there is no reason to use version 3.2.0 of this package. you can downgrade to version 3.1.0.
