### ISSUE TITLE
When use this widget inside tab bar view, it gets refresh every time the tab is switch back

### ISSUE THREAD

**Issue by SeasonLeee** [EdsonBueno/infinite_scroll_pagination#31]
Let's say I have tab1, tab2, etc

Currently I only have two tabs but I think the problem is the same in three tabs or more.

So, when I switch from tab1 to tab2, then I go back from tab2 to tab1, the refresh mechanism is triggered in tab1... why? Memory related issue? Or is there a property I can control this behavior?

To my understanding, there's already a property `addAutomaticKeepAlives`... so, why would such things still happen? 

Thanks in advance!

**Comment by EdsonBueno** [comment]
Hi @SeasonLeee.
Did you use the `with AutomaticKeepAliveClientMixin<YourStatefulWidget>` when defining your `State` class?

Your entire widget and consequently your `PagingController` are being recreated every time. This is the reason behind the refreshes.
This has nothing to do with the package. Even if your list wasn't paginated and you were using a regular `ListView` you would still find this problem. That's why I'm closing this issue.
Thank you!
