### ISSUE TITLE
PagedListView can't properly fetch data inside SingleChildScrollView 

### ISSUE THREAD

**Issue by 3kdeveloper** [EdsonBueno/infinite_scroll_pagination#335]
When I use PagedListView outside SingleChildScrollView it works fine. It fetches the data when I scroll to the bottom, See the code below.

`PagedListViewWidget(`
`  pagingController: _pagingController,`
`  padding: EdgeInsets.symmetric(vertical: 20.pv),`
`  itemBuilder: (context, transfer, index) => BookingTileWidget(`
`    transfer: transfer,`
`    pagingController: _pagingController,`
`    index: index,`
`  ),`
`  placeHolderWidget: Padding(`
`    padding: EdgeInsets.only(bottom: 50.pv),`
`    child: PlaceHolderWidget(`
`      child: BookingTileWidget(`
`        transfer: TransferModel(),`
`        pagingController: _pagingController,`
`        index: -1,`
`      ),`
`    ),`
`  ),`
),

But when I put it inside SingleChildScrollView it fetches all data page by page (on first attempt) without any scrolling o.

`SingleChildScrollView(`
`  physics: const BouncingScrollPhysics(),`
`  child: Column(`
`    children: [`
`      PagedListViewWidget(`
`        pagingController: _pagingController,`
`        padding: EdgeInsets.symmetric(vertical: 20.pv),`
`        physics: const NeverScrollableScrollPhysics(),`
`        itemBuilder: (context, transfer, index) => BookingTileWidget(`
`          transfer: transfer,`
`          pagingController: _pagingController,`
`          index: index,`
`        ),`
`        placeHolderWidget: Padding(`
`          padding: EdgeInsets.only(bottom: 50.pv),`
`          child: PlaceHolderWidget(`
`            child: BookingTileWidget(`
`              transfer: TransferModel(),`
`              pagingController: _pagingController,`
`              index: -1,`
`            ),`
`          ),`
`        ),`
`      ),`
`    ],`
`  ),`
`)`

**Comment by osmancan23** [comment]
Yes . I am getting the same error too

**Comment by clragon** [comment]
`PagedListViewWidget` is already a scrollable Widget and cannot be placed inside another scrollable Widget. 
You dont need to do this, and you shouldnt. 
If you need to have other elements that scroll _with_ the Paged widget, you can use a `CustomScrollView` plus the corresponding Paged Sliver variant, like `PagedSliverList`.

**Comment by osmancan23** [comment]
> `PagedListViewWidget` is already a scrollable Widget and cannot be placed inside another scrollable Widget. You dont need to do this, and you shouldnt. If you need to have other elements that scroll _with_ the Paged widget, you can use a `CustomScrollView` plus the corresponding Paged Sliver variant, like `PagedSliverList`.

Yes, scrollability is already available in the pagination list view, but since I want visibility under the bottom bar on my screen, I need to make a scaffold extend body true and wrap it with a scroll view. When you do it this way, it automatically sends requests one after the other. 

I want a view like this:
![Simulator Screenshot - iPhone 15 - 2024-07-06 at 17 13 24](https://github.com/EdsonBueno/infinite_scroll_pagination/assets/83430594/1b283fc7-775d-49aa-8736-4fd079a98276)

If I don't use scroll view, I get an image like this: 

![Simulator Screenshot - iPhone 15 - 2024-07-06 at 17 14 47](https://github.com/EdsonBueno/infinite_scroll_pagination/assets/83430594/d612fd6b-f05a-4029-a51e-a97c551b5b78)
