### ISSUE TITLE
More than one request gets triggered when specifying list cacheExtent

### ISSUE THREAD

**Issue by ibrahimEltayfe** [EdsonBueno/infinite_scroll_pagination#339]
When specifying the cacheExtent value in the list, the PagingController triggers multiple requests (fetches page 1 and page 2), even when the user has not scrolled yet.
```
PagedListView(
  cacheExtent: context.height * 3,
  ...
```

**Comment by clragon** [comment]
indeed, this is because extending the cache extent exends the viewport of the listview, therefore building more items, therefore hitting the threshold items and triggering a page request.

logically, this seems sound. if you want more of the list to be loaded ahead of time, then more items have to be loaded.
I am not sure how we could possibly "fix" this.
