### ISSUE TITLE
[Feature] Cache the initial data

### ISSUE THREAD

**Issue by Meshkat-Shadik** [EdsonBueno/infinite_scroll_pagination#351]
## Use Case  
The problem arises when the list view initially loads data and the user navigates away or the app goes into the background. When the user returns, the data is re-fetched even if the content has not changed. This re-fetching can lead to unnecessary API calls and a suboptimal user experience, especially for apps with low bandwidth or high-latency conditions.  

## Proposal  
Enable caching of the initial data fetched by the pagination controller, allowing the widget to display previously loaded data without requiring a re-fetch.  

### Key Features  
1. **Optional Caching**  
   - Add a flag to the `PagedListView` or `PagingController` (e.g., `enableCache: true`).  
   - When enabled, the controller should retain the loaded data in memory until explicitly cleared.  

2. **Manual Cache Management**  
   - Provide methods like `clearCache()` and `invalidateCache()` to allow developers to manage the cache programmatically.  

3. **Persistence Support** *(optional)*  
   - Optionally integrate with local storage for persistence across app restarts.  

### Implementation Details  
- Store the initial page's data in a local variable within the `PagingController`.  
- On widget rebuilds, check if cached data is available before attempting to load data from the source again.  
- Ensure the cache respects data consistency, such as invalidating on pull-to-refresh or changes in the query parameters.  

## Alternatives Considered  
- Implementing this feature manually by storing the fetched data outside of the `PagingController` in a separate state management solution. While feasible, it increases boilerplate code and undermines the convenience of using the `infinite_scroll_pagination` package.  

## Benefits  
- Reduces redundant API calls, saving bandwidth and improving performance.  
- Enhances user experience by reducing loading times when returning to a previously loaded screen.  
- Simplifies developer effort by encapsulating caching logic within the package.  

## Example Code  
```dart
final pagingController = PagingController<int, Item>(
  firstPageKey: 0,
  enableCache: true, // Enables caching of the fetched data.
  cacheTime: Duration(minutes:5), // this can be optional, by default this should hold a certain duration like 1 min
);

// Manually clear or invalidate the cache if necessary.
pagingController.clearCache();

**Comment by clragon** [comment]
Hi,

Paged Views and their Controllers do not rerequest the data they have loaded, as long as they are not destroyed.
What you are experiencing is most likely an issue in your code where the PagingController is recreated instead of retained.

Adding caching to the PagingController would not fix this issue, as the cache would be destroyed and recreated alongside the PagingController.

If you require your data to be cached, we recommend implementing the caching inside of your API layer.
There are many packages that can help you with this, like [dio_cache_interceptor](https://pub.dev/packages/dio_cache_interceptor).

Caching is very far out of the scope of this package, and will not be implemented. 
Thank you for your suggestion.
