### ISSUE TITLE
[Feature Request] Add pageSize property to PagingController so it knows if the last page has been fetched

### ISSUE THREAD

**Issue by oliatienza** [EdsonBueno/infinite_scroll_pagination#53]
Let the `PagingController` handle the conditional below by letting it know the `pageSize`. This could clean up a lot of boilerplate

```
 if (isLastPage) {
        _pagingController.appendLastPage(newItems);
      } else {
        final nextPageKey = pageKey + newItems.length;
        _pagingController.appendPage(newItems, nextPageKey);
      }
```

**Comment by EdsonBueno** [comment]
You have to keep in mind there are different pagination strategies.
Some of them use the page number as the index, others (like your example) uses the number of items to offset, others use a String token to identify the next page. 
That's why `PagingController` is designed this way.
You can read further [here](https://nordicapis.com/everything-you-need-to-know-about-api-pagination/).
