### ISSUE TITLE
There is no item count in PageGridView

### ISSUE THREAD

**Issue by hongfeiyang** [EdsonBueno/infinite_scroll_pagination#57]
PageGridView already supports many apis like GridView, but it lacks one key component itemCount, is there a way to get this api back?

**Comment by EdsonBueno** [comment]
Hi @hongfeiyang.
Are you talking about the `itemCount` parameter on [GridView.builder](https://api.flutter.dev/flutter/widgets/GridView/GridView.builder.html) constructor?
If you are, it doesn't make sense to have that parameter when talking about pagination, because you don't know what the `itemCount` will be when creating the `PagedGridView`.

What do you need it for?
If you need to know how many items are loaded at any point in time, you can use `_pagingController.itemList.length`.

**Comment by hongfeiyang** [comment]
I am talking about something like this: https://stackoverflow.com/questions/53967624/flutter-error-rangeerror-index-invalid-value-not-in-range-0-2-inclusive, providing an item count seems to fix it.
