### ISSUE TITLE
Error with the restorationId

### ISSUE THREAD

**Issue by vexa** [EdsonBueno/infinite_scroll_pagination#6]
hi i got the following error when i use your component 

.org/infinite_scroll_pagination-2.2.0/lib/src/ui/paged_grid_view.dart:65:11: Error: No named parameter with the name 'restorationId'.
          restorationId: restorationId,

**Comment by EdsonBueno** [comment]
Hi @vexa . That's because you're not using the latest stable Flutter version. You have two alternatives:
1. Upgrading your Flutter to the latest stable version (1.22).
2. Downgrading the infinite_scroll_pagination package in your pubspec.yaml to version 2.1.0+1.

I strongly recommend the first, because you'll have to do it anyway at one point.
