### ISSUE TITLE
[BUG] The listener of addPageRequestListener should not be called when status is PagingStatus.loadingFirstPage

### ISSUE THREAD

**Issue by basketball-ico** [EdsonBueno/infinite_scroll_pagination#90]
To fix it I had to add some validations in my BLoC or just

```dart
   _pagingController.addPageRequestListener((pageKey) {
      if (_pagingController.value.status != PagingStatus.loadingFirstPage) {
        widget.bloc.loadMoreItems();
      }
    });
```

**Comment by EdsonBueno** [comment]
Hi @basketball-ico .
Why is that a bug? If the status is `loadingFirstPage`, it's because we don't have any items, and if we don't have any items, we should request a new page.
I'm closing the issue for now, but feel free to continue the discussion.

**Comment by basketball-ico** [comment]
Thanks, I understand that if you are loading the first page it is because you already made the first request to load the first page, so you should only call the next page, when the first page is loaded and has not reached max page,, that is, in "onGoing" , if you call it before that, the request for the first and second page would be made almost immediately, causing bugs,

**Comment by EdsonBueno** [comment]
It makes perfect sense, but in the end it all seems to be about "taste".
By calling the listener for **every** page (including the first) developers can have a unique way of handling page fetches. Otherwise, you'd have to write different code for handling the first and the subsequent pages.
Thank you for your feedback
