### ISSUE TITLE
Not registering a listener immediately makes it impossible to add one later

### ISSUE THREAD

**Issue by martipello** [EdsonBueno/infinite_scroll_pagination#92]
for instance this fails 

  final _pagingController = PagingController<int, Booking>(firstPageKey: 0);

  void _initializeBookingPagingAdapter() async {
    _bookingPagingAdapter.pagingController = _pagingController;
    Future.delayed(Duration(seconds: 10), _addPageRequestListener);
  }

  void _addPageRequestListener() {
    _bookingPagingAdapter.addPageRequestListener();
  }

// PagingAdapter
 void addPageRequestListener() {
    pagingController.addPageRequestListener(_fetchPage);
  }

I'm actually trying to initialize it and then wait for my filter data to be reader before attaching a listener because the listener triggers the call to the server so in my instance i initialize the paging controller register the listener (this calls my service) then my filter data is ready so i update this and pass it to the paging adapter and call refresh so this is now 2 calls to the server when only one would suffice if i could have the paging controller wait for the listener to be registered

**Comment by EdsonBueno** [comment]
Hi @martipello .
I don't think what you're trying to do is the right approach, and changing the package to accommodate your scenario doesn't make sense.
The thing is: the page is requested even if your filter is not ready yet, because the package has nothing to do with it.

What I think you should do is: Inside your `_fetchPage`, don't make the request if your filter is not ready yet, and then, when your filter is ready, just call `_fetchPage`.

I'm closing this issue for now, but feel free to continue the discussion.
Thanks for the feedback.

**Comment by martipello** [comment]
This is exactly what I was going to do as a work around so seems fine to me many thanks
